### PR TITLE
BUG: add ssl_host_name setting for https urls and parsing HTTP AUTH credentials from URI on Request instance creating.

### PR DESCRIPTION
**Pull request by alebedev80**
During production use i've found an issue with connection to https://https://uds.hasene.online. Request failed with warning:

`WARNING	swSSL_connect: SSL_connect(fd=9) failed. Error: (null)[1|0].`

After investigation fix https://github.com/swoole/swoole-src/commit/77876aad4b423fd2538152d86ce7f63fd075fe71 i've added 'ssl_host_name' with host name for SSL request.

Also added parsing HTTP AUTH credentials from URI on Request instance creating.

PHP version: 7.3.3

Swoole:

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.1
Built => Mar 27 2019 15:38:16
coroutine => enabled
kqueue => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2r  26 Feb 2019
http2 => enabled
pcre => enabled
zlib => enabled
brotli => enabled
async_redis => enabled

### CODE REVIEW

**Comment by twose** [comment]
Nice pr.
In fact, ssl_host_name is automatically added in the latest swoole version.
About auth, I think it should be generated before the request exec(URI is not immutable), could you make some changes?

**Comment by alebedev80** [comment]
>  I think it should be generated before the request exec(URI is not immutable), could you make some changes?
@twose yes uri is immutable. but in that case user will not be able override auth settings from url by \Swlib\Saber\Request::withBasicAuth() but i think he should.

But maybe i'm wrong please provide where do you prefer to move \Swlib\Saber\Request::initBasicAuth()

**Comment by alebedev80** [comment]
@twose added test \Swlib\Tests\Saber\SaberTest::testAuthOverrideUserInfoInURI

**Comment by twose** [comment]
Merged, thanks.
I will do more checks before release.

**Comment by alebedev80** [comment]
Thank you! Will wait release!

**Pull request merged**
